service: default
runtime: python38

basic_scaling:
    max_instances: 2
    idle_timeout: 10m

resources:
    cpu: 1
    memory_gb: 0.5
    disk_size_gb: 10

#entrypoint: python main.py
entrypoint: gunicorn -b :8050 main:server
